version: '3.5'
services:
  mongodb:
    container_name: ${NAME}
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MANGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MANGO_ROOT_PW}


#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MANGO_ROOT}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MANGO_ROOT_PW}
#      ME_CONFIG_MONGODB_URL: mongodb://${MANGO_ROOT}:${MANGO_ROOT_PW}@mongodb:27017/
#
