version: '3.5'
services:
  mongodb:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo
    restart: always
    ports:
      - ${MONGO_HOST_PORT}:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PW}
    volumes:
      - /data/db：/data/db
    privileged: true

  server:
    container_name: ${SERVER_CONTAINER_NAME}
    build:
      context: /data:data/db
    restart: always
    privileged: true
    depends_on:
      - mongodb
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    
  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MANGO_ROOT}
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MANGO_ROOT_PW}
#      ME_CONFIG_MONGODB_URL: mongodb://${MANGO_ROOT}:${MANGO_ROOT_PW}@mongodb:27017/
#


networks:
  server:
    driver: ${NETWORK_DRIVER}